name: Deploy GAS

on:
  push:
    branches: [main]
    paths:
      - 'gas/**'
      - '.github/workflows/deploy-gas.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install clasp
        run: npm install -g @google/clasp
      
      - name: Setup clasp authentication
        run: |
          echo '${{ secrets.CLASP_CREDENTIALS }}' > ~/.clasprc.json
      
      - name: Push to GAS
        run: |
          cd gas
          clasp push --force
      
      - name: Deploy new version
        run: |
          cd gas
          VERSION=$(clasp version "Deploy from GitHub Actions")
          clasp deploy --versionNumber $VERSION --description "Automated deployment"